### ISSUE TITLE
Undefined variable: imageContainer and pasteData when using TinyMCE

### ISSUE THREAD

**Issue by arstar** [PendalF89/yii2-filemanager#1]
When using the filemanager using TinyMCE the variables imageContainer and pasteData are not assigned to the modal view causing an Undefined variable.

See pendalf89\yii2-filemanager\widgets\TinyMce.php line 82

**Comment by invaderhd** [comment]
I have exactly the same error. How can I get the TinyMce working?

**Comment by arstar** [comment]
We copied the repo and added some fixes. You can find them here: https://bitbucket.org/finfiles/yii2-filemanager.git

**Comment by PendalF89** [comment]
Arstar, ivan solved this problem, for which he thanks a lot!
