### ISSUE TITLE
Is this extension maintained?

### ISSUE THREAD

**Issue by mtangoo** [PendalF89/yii2-filemanager#18]
I can see most of Issues have no comment whatsoever. Wanted to know if it is abandoned or not.
Thanks

**Comment by PendalF89** [comment]
Sorry, but I have no time now to support this module.

**Comment by mtangoo** [comment]
Which is fair, and I appreciate your answer. But Some users (Me included) might want to help you via PR or any other means since we use your extension. But to be frank, There are some difficult to understand modus operandi of extension and hence we fail to lender help we badly want to.

For example I try to battle with #17. All I need is to know how extension generates URL  in relation to configurations. I tried to go thru code and there is a lot of interdepending codes.

To cut story short, I agree on supporting, but I request you to help just to give direction whenever possible.
Thanks making extension by the way, its very useful.
