### ISSUE TITLE
Composer cannot find package

### ISSUE THREAD

**Issue by con322** [PendalF89/yii2-filemanager#2]
Hi your file manager looks awesome, I was just trying to install in via composer and get the following message:

    - The requested package pendalf89/yii2-filemanager could not be found in any version, there may be a typo in the package name.

Any ideas?

**Comment by PendalF89** [comment]
Hi con322!
Package is available https://packagist.org/packages/pendalf89/yii2-filemanager
Try next code in your composer.json:
```json
"minimum-stability": "dev",
"prefer-stable" : true
```
Also see here: http://stackoverflow.com/questions/23086204/composer-required-packages-with-differing-levels-of-minimum-stability

**Comment by con322** [comment]
I tried using "dev-master" instead of "*" however I'll try you suggestion when i get home, awesome work by the way.

**Comment by PendalF89** [comment]
Thanks!

**Comment by con322** [comment]
I get the following message after doing what you suggested

                                                                                   
  [Composer\DependencyResolver\SolverProblemsException]                        
    Problem 1                                                                  
      - Installation request for yiisoft/yii2 * -> satisfiable by yiisoft/yii  
  2[2.0.3].                                                                    
      - yiisoft/yii2 2.0.3 requires bower-asset/jquery.inputmask 3.1.* -> no   
  matching package found.                                                      
    Problem 2                                                                  
      - yiisoft/yii2 2.0.3 requires bower-asset/jquery.inputmask 3.1.* -> no   
  matching package found.                                                      
      - pendalf89/yii2-filemanager dev-master requires yiisoft/yii2 * -> sati  
  sfiable by yiisoft/yii2[2.0.3].                                              
      - Installation request for pendalf89/yii2-filemanager * -> satisfiable   
  by pendalf89/yii2-filemanager[dev-master].                                   
  Potential causes:                                                            
   - A typo in the package name                                                
   - The package is not available in a stable-enough version according to you  
  r minimum-stability setting                                                  
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussi  
  on> for more details.                                                        
  Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further c  
  ommon problems.

**Comment by PendalF89** [comment]
Try this in comman line
```
composer global require "fxp/composer-asset-plugin:1.0.0-beta3"
```

**Comment by con322** [comment]
Thanks for your suggestion, I got it working by adding the following to composer,

         "pendalf89/yii2-tinymce": "dev-master",
        "pendalf89/yii2-filemanager": "dev-master"

**Comment by jinostart** [comment]
composer require --prefer-dist pendalf89/yii2-filemanager "dev-master"

**Comment by jinostart** [comment]
Try this in command line

**Comment by jinostart** [comment]
Try this in command line
composer require --prefer-dist pendalf89/yii2-filemanager "dev-master"

**Comment by jinostart** [comment]
Problem 1
    - The requested package minimum-stability could not be found in any version, there may be a typo in the package name.

Try this in command line
$ vim composer.json
{
    "minimum-stability": "dev",
    "require": {
      ……
    }
}
