### ISSUE TITLE
How to changes the function to create thumnail?

### ISSUE THREAD

**Issue by phamnhatcn06** [PendalF89/yii2-filemanager#22]
Hello.
I'm using yii2-filemanager you're created. It's very helpful. But I have a problem:
The default mode when create thumbnail images is THUMBNAIL_OUTBOUND. But I want to change it to THUMBNAIL_INSET. I'm looking for a config but It didn't have a config about it. Hope you to help me! Thanks a lot.

**Comment by PendalF89** [comment]
Hello!
Thank you for using filemanager. Sorry, but i don't understand what you mean about thumbnails.

**Comment by phamnhatcn06** [comment]
OK. when I upload an image,extension will resize it to some thumnail. I see you use extension yii2-imagine to resize thumbnail. But the mode default is THUMBNAIL_OUTBOUND. It's mean my image will be cropped. But I want to keep it's original proportions (width : height). So I want to config in the main.php by code to change mode to THUMBNAIL_INSET.How can I do it? Thank so much.

**Comment by PendalF89** [comment]
Aaa, i'm understand you!
Sorry, but it's not support in current version.

**Comment by phamnhatcn06** [comment]
Hope to have it in next version. Thank you.
Aa, I have a question in this extension: How can i config for only upload image? because I only want to upload image to my server? Thanks so much!

**Comment by PendalF89** [comment]
If you want upload something files to server, you can use this extension: https://github.com/2amigos/yii2-file-upload-widget
