### ISSUE TITLE
Choose Language default

### ISSUE THREAD

**Issue by phamnhatcn06** [PendalF89/yii2-filemanager#28]
Hello. Hope you don't mind with some my issues.
I have updated my region language folder but I don't know how to setting this extension run with my region language. I'm looking forward from you soon. Thanks so much. (y)

**Comment by PendalF89** [comment]
You can set you language in application config https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-i18n.md

**Comment by phamnhatcn06** [comment]
OK..thanks.
