### ISSUE TITLE
Styling missing 

### ISSUE THREAD

**Issue by con322** [PendalF89/yii2-filemanager#3]
Apologies about opening another issue however I seem to have none of the styling that is seen in your screen shots (i really want to get this installed as it is awesome).

I have installed it and uploads are working although I need to configure the path properly, however there's no styling. 

![github_filemanager_error](https://cloud.githubusercontent.com/assets/6308063/6697128/69b92370-cce6-11e4-90c9-849bac2ec1ad.jpg)

Any ideas?

**Comment by PendalF89** [comment]
Try experimenting with ways of setting.

**Comment by con322** [comment]
Ways option? is that related directly to your extension or yii2?

**Comment by con322** [comment]
Could it be something to do with the fact it's being rendered/displayed in an iframe therefore the iframe isn't getting my stylesheet or does the filemanager/extension come with it's own stylesheet?

**Comment by PendalF89** [comment]
Please, see this module settings block:
```
'routes' => [
            // Base absolute path to web directory
            'baseUrl' => '',
            // Base web directory url
            'basePath' => '@frontend/web',
            // Path for uploaded files in web directory
            'uploadPath' => 'uploads',
        ],
```

**Comment by con322** [comment]
It seems the iframe is getting any css assets other than is this meant to be the case or should it be getting bootstrap styles as well

    http://localhost:8888/advanced/assets/2c3c182c/css/filemanager.css

**Comment by con322** [comment]
What would be the best way for me to debug this? (just so I can try do it myself and stop bugging you)

It seems that your some sort of asset problem, as my theme assets aren't being used within the file iframe/pages them selves.

Also when I use the form field bootstrap modal js file ins't being registered within my view, am I missing something? As I assumed when the field was used the js would be added automatic as a dependency.

**Comment by con322** [comment]
I can fix the styling by adding to the extension however not to sure whether this should be done? The view requires app assets which currently isn't being used only file manager asset is.

**Comment by PendalF89** [comment]
Sorry for delay.
What show next code?
```
Yii::getAlias('@web');
Yii::getAlias('@webroot');
```
You use advanced, or basic template?
And show your module configuration.

**Comment by con322** [comment]
No worries thanks for trying to assist though.

I am using improved advanced template, the module configuration is exactly as is in documentation. If I add app asset to the iframe/file manager view the styling is fixed. However bootstrap/modal js is not register in view, is this because of the ways it's done as normally in yii2 you have to use yii/bootstrap/widget and then use the echo modal widget.

**Comment by PendalF89** [comment]
I think, that this problem related with wrong path in config. Try to use Yii::getAlias('@webroot') value in "basePath" option.

**Comment by con322** [comment]
Got my images working hover it means that when changing to server I'll have to remove the advanced bit
used the following:

                   'basePath' => '@webroot',
                // Path for uploaded files in web directory
                'uploadPath' => 'advanced/uploads',

Only problem now is the modal javascript modal, how is this meant to be registered within the extension/widget as it's not being included within head?

**Comment by con322** [comment]
Thanks for the suggestion, this is bugging me as I must be doing something wrong.

The images are being uploaded the the right directory but the path they are is is wrong or it may be my localhost setup.

I have MAMP point to htdocs and then my yii2 stuff in a folder called advanced.

The image path in the database is uploads/.... rather than advanced/uploads...

**Comment by PendalF89** [comment]
Great!
For js maybe help clean asset folder after your experiments?

I think I understand what the problem is. 
Now your config this:
```
'basePath' => '@webroot',
// Path for uploaded files in web directory
'uploadPath' => 'advanced/uploads',
```

Because you web folder is "http://localhost:8888/advanced/", just set as 'basePath' next value: '@webroot/advanced'.
For the future make a separate virtual host for project.

**Comment by con322** [comment]
I have changed my installation no longer requires /advanced however still no js do I need to reinstall extension. How us bootstrap js. Isn't bootstrap a dependency for the extension/widget though so I shouldn't really need to change anything should I? Anyways I know of a way to include it without echoing widget so for the time being I'll do that.

**Comment by con322** [comment]
Solved thank you and awesome extension, I used the following 

        public $depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapPluginAsset',
            '\rmrevin\yii\fontawesome\AssetBundle',
       ];

**Comment by Milivoje422** [comment]
Hi guys, i have one issue with plugin, check this photo. 
There it seems the plugin is not loading any javascript files , 
i'm not sure how to fix this , any ideas ?
The thing is, there is nowhere I can find those files
![screenshot 6](https://cloud.githubusercontent.com/assets/16079428/21881702/a5773662-d8a7-11e6-993e-f93e5a043f84.png)
