### ISSUE TITLE
install extension error

### ISSUE THREAD

**Issue by saepulm** [PendalF89/yii2-filemanager#5]
I've followed the instructions there but error
![screenshot_121](https://cloud.githubusercontent.com/assets/7220303/6796152/0784f384-d220-11e4-9c6d-0719f6172df7.jpg)

**Comment by PendalF89** [comment]
Hi Saepulm!
You need instal zlib extension for you php.
Please, see here: http://stackoverflow.com/questions/23719738/zlib-decode-data-error-using-composer-in-the-doctrine2-tutorial-solved
