### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by iliyanz** [PendalF89/yii2-filemanager#63]
First, I want to thank you and suggest an update.
Filemagener can be access by url without login.
I updated FileController function behaviors like this:

`public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['index', 'filemanager', 'uploadmanager', 'upload', 'update', 'delete','resize','info'],
                'rules' => [
                    [
                        'actions' => ['index', 'filemanager', 'uploadmanager', 'upload', 'update', 'delete','resize','info'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'update' => ['post'],
                ],
            ],
        ];
    }`

**Comment by PendalF89** [comment]
Thanks for your observation!
Can you create pull request with you correction?

**Comment by iliyanz** [comment]
Yes, of course. I will make it today.
На 2.07.2016 г. 4:54 "Boris Zabolotskikh" <notifications@github.com> написа:
