### ISSUE TITLE
Error in filename

### ISSUE THREAD

**Issue by Dr1N** [PendalF89/yii2-filemanager#65]
[https://github.com/PendalF89/yii2-filemanager/blob/master/widgets/**TinyMCE.php**](https://github.com/PendalF89/yii2-filemanager/blob/master/widgets/TinyMCE.php)

Class name does not match the file name

_class TinyMce extends InputWidget_

**Comment by PendalF89** [comment]
Fixed

**Comment by PendalF89** [comment]
Fixed
