### ISSUE TITLE
Mediafile::getThumbs() should return an array even if unserialize() returned null

### ISSUE THREAD

**Issue by chaimleich** [PendalF89/yii2-filemanager#68]
Consider the following two pieces of code:

    public function getThumbs()
    {
        return unserialize($this->thumbs);
    }

and

    public function deleteThumbs(array $routes)
    {
        $basePath = Yii::getAlias($routes['basePath']);

        foreach ($this->getThumbs() as $thumbUrl) {
            unlink("$basePath/$thumbUrl");
        }

        unlink("$basePath/{$this->getDefaultThumbUrl()}");
    }

I encountered a situation where the thumbnails weren't stored properly (max process time issue - not important :)), which caused deleteThumbs to break because the `foreach()` was being run on a null value.

My suggestion: to make the code more bullet-proof, either modify getThumbs as follows:

    public function getThumbs()
    {
        return unserialize($this->thumbs) ?: [];
    }

or modify deleteThumbs() to cast the result of getThumbs as an array:

    public function deleteThumbs(array $routes)
    {
        $basePath = Yii::getAlias($routes['basePath']);

        foreach ((array)$this->getThumbs() as $thumbUrl) {
            unlink("$basePath/$thumbUrl");
        }

        unlink("$basePath/{$this->getDefaultThumbUrl()}");
    }

**Comment by chaimleich** [comment]
Similarly, if the original file did not save properly, then `Mediafile::deleteFile()` breaks. I would suggest modifying as follows:

    public function deleteFile(array $routes)
    {
        $basePath = Yii::getAlias($routes['basePath']);
        $filePath = "$basePath/{$this->url}";
        return file_exists($filePath) ? unlink($filePath) : false;
    }

**Comment by PendalF89** [comment]
Thanks for solutions and pull request, chaimleich!
