### ISSUE TITLE
Problem with routes.

### ISSUE THREAD

**Issue by Godscreature** [PendalF89/yii2-filemanager#8]
Hello. Thank you for this great module!

I started to learn yii2 a few week ago. I never using this framework (yii1) never before. Excuse me if I writing something stupid..

 In my project this module has one problem. With routes...
I use Yii2 advanced. I included this filemanager in backend. I tried to configured common/config/main.php:

    'modules' => [
        'filemanager' => [
            'class' => 'pendalf89\filemanager\Module',
            // Upload routes
            'routes' => [
                // Base absolute path to web directory
                'baseUrl' => '',
                // Base web directory url
                'basePath' => '@frontend/web/images/',
                // Path for uploaded files in web directory
                'uploadPath' => 'uploads',
            ],
            // Thumbnails info
            'thumbs' => [
                'small' => [
                    'name' => 'Small',
                    'size' => [100, 100],
                ],
                'medium' => [
                    'name' => 'Medium',
                    'size' => [300, 200],
                ],
                'large' => [
                    'name' => 'Big',
                    'size' => [500, 400],
                ],
            ],
        ],
    ]

But images not showing. Image files - has writed to database, has uploaded to path which I configured - '/frontend/web/images/uploads/YYYY/MM'. And I have a field 'url' in database = '/uploads/2015/04/mestoraspolozhenie-xolodilnika.jpg' for example, but folder with my image is '/frontend/web/images/uploads/2015/04/mestoraspolozhenie-xolodilnika.jpg', so I added something to config in my backend/config/main.php:

    'modules' => [
        'filemanager' => [
            'routes' => [
                'content_image_path' => '/frontend/web/images',
            ],
        ],
    ],

and I included this in two methods of models/Mediafile.php:

method №1: getDefaultThumbUrl
public function getDefaultThumbUrl($baseUrl = '')
{
// ....... code ......
// standart code:
// return "$dirname/$filename-{$width}x{$height}.$extension";
// my code:
return Yii::$app->getModule('filemanager')->routes['content_image_path']."$dirname/$filename-{$width}x{$height}.$extension";
}

method №2: getImagesList
public function getImagesList(Module $module)
{
// ....... code ......
foreach ($thumbs as $alias => $url) {
  $preset = $module->thumbs[$alias];
  // standart code:
  // $list[$url] = $preset['name'] . ' ' . $preset['size'][0] . ' × ' . $preset['size'][1];
  // my code:
  $list[$module->routes['content_image_path'].$url] = $preset['name'] . ' ' . $preset['size'][0] . ' × ' . $preset['size'][1];
}

$originalImageSize = $this->getOriginalImageSize($module->routes);
// standart code:
// $list[$this->url] = Module::t('main', 'Original') . ' ' . $originalImageSize;
// my code:
$list[$module->routes['content_image_path'].$this->url] = Module::t('main', 'Original') . ' ' . $originalImageSize;
return $list;
}

After this manipulations the problem is gone. I hope so....

Excuse me, friend, if something wrong. It's my first Issue))).

**Comment by PendalF89** [comment]
Привет! Я так понимаю, с тобой можно на русском :)
Рад что тебе понравился мой модуль!
У меня только один вопрос: по каким урлам доступны backend и frontend приложения?
Кстати, yii2 лучше изучать с basic приложения. Функционалом они никак не отличаются, отличаются только архитектурой и удобством.

**Comment by Godscreature** [comment]
Привет)))
Можно на русском. Я вообще около 4-х лет программирую, то там то сям... А это - взялся учить Yii, и на GitHub впервые полез, так что все новое)))

Yii - неделю думал и разбирался - какие тенденции ( Yii1 или Yii2 ) и что мне подойдет ( basic или advanced ), короче решил на Yii2 advanced клепать, в принципе, не жалею пока, правда, башка трещит - много всего параллельно приходится колупать и разбирать)))

урлы:
frontend - http://domain.com.ua/
backend - http://domain.com.ua/admin/

В принципе, еще один момент интересует, спрошу, если можно:
Хочу файлы разделить - один файлменеджер, но файлы - контентные картинки всякие, и еще файлы - типа внутри-админочного "документооборота".

Так вот обычные контент-файлы типа сделал, а на те другие - хочу отдельную папку, и что б файлменеджер сохранял то туда то сюда... ну и придется еще один путь добавить для этого по идее..

Может черкнешь пару слов - на счет этого подхода? Нормально это или ненужный гемор?

**Comment by PendalF89** [comment]
Хм... ну вроде всё правильно должно быть, если фронтенд доступен по корню, а админка вынесена на /admin, то доступ должен быть 100%.
Я заметил одну деталь:  'basePath' => '@frontend/web/images/', - у тебя слеш на конце, его ведь не должно быть. И если не поможет, попробуй поставить в 'baseUrl' => '/',

"Так вот обычные контент-файлы типа сделал, а на те другие - хочу отдельную папку, и что б файлменеджер сохранял то туда то сюда... ну и придется еще один путь добавить для этого по идее.."
- не, так делать не стоит, это избыточность, запутаешься ведь потом)

**Comment by Godscreature** [comment]
А что, все файлы вперемешку бросать в одну папку?

**Comment by PendalF89** [comment]
Почему нет?
Если у тебя файлы, которые относятся к твоей теме (дизайну), то конечно их лучше всего отдельно куда-то положить.

**Comment by Godscreature** [comment]
ну с этими - ясно, я про контентные - картинки всякие, pdf может..

**Comment by PendalF89** [comment]
Это я бы хранил в одном месте.

**Comment by Godscreature** [comment]
Можешь помочь? Перестало файлы отображать загруженные.. Например файл залитый
http://medcarethailand.ru/frontend/web/images/uploads/2015/04/24234357kreshchenie_rebenka-128x128.jpg

по этому же пути не доступен - пишет not found, хотя он 1000% есть там я вижу его там по ftp

**Comment by PendalF89** [comment]
Ммм.. не вижу проблемы, например, я только что залил картинку (см. http://medcarethailand.ru/admin/article/update?id=10) и она отображается в редакторе.
И да, смени стандартный пароль ;)

**Comment by Godscreature** [comment]
Та полдня сидел в итоге htaccess создал в папке /frontend/web - начало отображать..
слушай, я наверно слишком много прошу, но все же, есть ли способ и главное возможность как-то переписываться с тобой (skype, социалки), что б спрашивать по YII2 ?

**Comment by PendalF89** [comment]
Да не вопрос, не ты первый, не ты последний кто меня об этом просит, добавляйся ко мне в друзья: vk.com/vaiho :)

**Comment by Godscreature** [comment]
послал заявку. Эту issue я как то должен закрыть?

**Comment by PendalF89** [comment]
Да, можно закрыть

**Comment by Tivos** [comment]
Здравствуйте PendalF89.
у меня такие урлы:
frontend - http://domain.com.ua/
backend - http://admin.domain.com.ua/
.
файлы буду сохранять в frontend/web/uploads
Подскажите как настроить конфиг что-бы это организовать
  'filemanager' => [
            'class' => 'pendalf89\filemanager\Module',
            // Upload routes
            'routes' => [
                // Base absolute path to web directory
                'baseUrl' => '/',
                // Base web directory url
                'basePath' => '@frontend/web',
                // Path for uploaded files in web directory
                'uploadPath' => 'uploads',
            ],
        ],
так не работает(
так же нужно что-бы в админке отображались изображения в filemanager
