### ISSUE TITLE
Your requirements could not be resolved to an installable set of package

### ISSUE THREAD

**Issue by asadbekkuz** [PendalF89/yii2-filemanager#92]
I've not installed this package in yii2 framework.
**this is my composer.json require section.**
"minimum-stability": "stable",
    "require": {
        "php": ">=7.4.0",
        "yiisoft/yii2": "~2.0.45",
        "yiisoft/yii2-bootstrap5": "~2.0.2",
        "yiisoft/yii2-symfonymailer": "~2.0.3"
    },

**Comment by asadbekkuz** [comment]
how can fix them.  Error code lbellow.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires pendalf89/yii2-filemanager *, found pendalf89/yii2-filemanager[dev-master] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by PendalF89** [comment]
Hello! You can replace `"minimum-stability": "stable"` with `"minimum-stability": "dev"`.

**Comment by asadbekkuz** [comment]
thank you, bug is fixed .
