### ISSUE TITLE
how can I disable bootstrap asset of package ?

### ISSUE THREAD

**Issue by asadbekkuz** [PendalF89/yii2-filemanager#93]

**Comment by asadbekkuz** [comment]
Hello , my bootstrapp asset and package bootstrap asset  both include in my project. So , I must disable package's bootstrap.
my project's bootstrap v5, package bootstrap v3.

**Comment by PendalF89** [comment]
Hello! You can't disable bootstrap 3 in the package. But, you can disable bootstrap 3 assets in the Yii2 config. Example: https://forum.yiiframework.com/t/how-to-disable-yii2-pjax-asset-loading-automatically/86327

**Comment by asadbekkuz** [comment]
> Hello! You can't disable bootstrap 3 in the package. But, you can disable bootstrap 3 assets in the Yii2 config. Example: https://forum.yiiframework.com/t/how-to-disable-yii2-pjax-asset-loading-automatically/86327

Thank you for answer
